---
- hosts: app
  become: yes

  pre_tasks:
    - name: Checking for a properly OS distribution
      fail:
        msg: For a properly working of this playbook the Debian 9 is required
      when:
        - ansible_distribution_release != "stretch"

    - name: Upgrade the Debian distribution
      apt:
        update_cache: "yes"
        upgrade: "yes"

- import_playbook: install_docker.yml
- import_playbook: create_postgres_db&user.yml
